CREATE SCHEMA SISIDANG;

CREATE TABLE MAHASISWA(
	npm CHAR(10) PRIMARY KEY NOT NULL,
	nama VARCHAR(100) NOT NULL,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(20) NOT NULL,
	email VARCHAR(100) NOT NULL,
	email_alternatif VARCHAR(100),
	telepon VARCHAR(100),
	notelp VARCHAR(100)
);

CREATE TABLE TERM(
	tahun integer,
	semester integer,
	PRIMARY KEY (tahun, semester)
);

CREATE TABLE PRODI(
	ID integer PRIMARY KEY NOT NULL,
	NamaProdi VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE DOSEN(
	NIP VARCHAR(20) PRIMARY KEY NOT NULL,
	nama VARCHAR(100) NOT NULL,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	institusi VARCHAR(100) NOT NULL
);

CREATE TABLE MATA_KULIAH_SPESIAL(
	IdMKS integer,
	NPM CHAR(10) REFERENCES MAHASISWA(npm) ON DELETE CASCADE ON UPDATE CASCADE,
	Tahun integer REFERENCES TERM(tahun) ON DELETE CASCADE ON UPDATE CASCADE,
	Semester integer REFERENCES TERM(semester) ON DELETE CASCADE ON UPDATE CASCADE,
	Judul VARCHAR(250) NOT NULL,
	IsSiapSidang BOOLEAN DEFAULT FALSE,
	PengumpulanHardCopy BOOLEAN DEFAULT FALSE,
	IjinMajuSidang BOOLEAN DEFAULT FALSE,
	IdJenisMKS integer NOT NULL REFERENCES JENISMKS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(IdMKS, NPM, Tahun, Semester)
);

CREATE TABLE JENISMKS(
	ID PRIMARY KEY NOT NULL,
	NamaMKS VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE DOSEN_PEMBIMBING(
	IDMKS integer REFERENCES MATA_KULIAH_SPESIAL(IdMKS) ON DELETE CASCADE ON UPDATE CASCADE,
	NIPSaranPenguji VARCHAR(20) REFERENCES DOSEN(NIP) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(IDMKS, NIPSaranPenguji)
);