INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (52,73,' LOjHjzxVdNCwcCyzhxNI','rgFSaOJzd fzAklPfrPketNxEtyCgceHfn KtWlnRiftAQejGFxraXwykakMevlQBMaDUdNWtWqrlJkCLcS');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (53,42,'UzxFPDRAxfGJPAry mjuMfEMP','zruCluLUQ vihTLFBETEHofHewAilp');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (54,37,'ihmg gre lMkc','ckfihTSYfJQMoVkafmfKguJriKJDMlsWFuZZOtaVnrvMaxqvz CwJLOZabMcnhJrEfUuIjEn UX jFcEhrVMyH');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (55,30,'hr  b F QUWdBiCfkg','laThaSvBPhPXlFNB WKPgaFhlIViScC');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (56,49,'IyRmnMCvK dcDIUqF','XwXTkWzaEqOXidoJCXXEnwpLLzVeNGQUCbvKhCaEGqyWHDegSdCQOQvZiZIOplYANBUkqwxLR');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (57,66,'ytZuRjqPmcyENuIFpaHOymYLY dC','DsfVlMDHIPHwSOIBQLIrMfknjYa ui');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (58,39,'XEnoPvB rspqGmdRrTIN HwyZbbFWg','usWMBGvfGlaIqfcAsgSFtinaFMYcxgcfJnpQghDqOzdQWIJijKpdBEmsVinbygq  ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (59,26,'RYvDvsnrvnQvQmINQpxzOAQfZ','PtPuqFsWEYZrEeuQyrQbBkbaaRsDHzQAvObK N PhUyZSIKIdvH');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (60,53,'OrbjdyMziAxUb WKtAltlDA','JjhhZo qqWRirSmCdVo mmJyVPxAVQGJa wELjJ H fKUiRBRmrYFbcoHMXYpGhcGOiSTcmhucyuKRlNae StPUTMpRrvakASfO');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (61,18,'NiFTOcRQVKgZCksoh','TBDYOwfWgIkyGSCfZFmKOuEDObFCiDqxBrSqwNdsLRePnycsPyYCVMVRHpzvirEetM');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (62,54,'piHaoLQHFRQZXqRo gTChk','ipIwfQftRoldzVUAlzLmjicQMcxkevUWf myI');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (63,27,'LdiWAH yRL oTtRcti','kTwdTvsVCgBjhszsnyIXzDypcFmHjUZdHrokDZ QV');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (64,57,'dRzzVjRF HXz','wEZJofRhTkWEpqHlueGeaaB gHyjj');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (65,34,'vgzCqvkModtSg','cByHCgxttinrFODuHEpSINEbQxLwaBM lmgkFSRPTNOtKyErwxG eRkiXL qYnnxSCUGoIUfPeDG');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (66,57,'UODUQAMcfvLC','JlLDPUAxVaKzLbbBNNjGojvBRSPUFZXvfWSahSJscLqDzugkDwmcg PYXBYoPsvaBIyw');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (67,18,'iTkJgBsPFKx gZQk','YMXRIXvRNJqEKSlziVmhelm SWzYyZyUJoLQiIno zxVn');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (68,19,'IyeSUJlOVUnSTSakRHdrz','UaRcbOwbXWursBJjFdlvxFcpkCvWUBRyRQXlUjwgLgnojkmwYFDrYNoWl YGTPXONmJxsyJ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (69,14,'WEBvIBktYxHLtmUqJS NR','qPmTFjyyYVrOvWJhoDQtJEHcxwSxydGNXHGspGnJpKCQygauDWN DlDnQiRKxox HksbDjWzaeTQOLVJjU');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (70,61,'flbgBMFoqlWfzCDgB','GbbbkRezECYIKGNfEFUdsUL lgafPULvkxFzfiDIwB nAATkGgyKEnewcfdjUztlRQwEU kOPsiLgsQluiZlzHDhtnGWGis');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (71,43,'b aBxIGoC SIhaJGIu','yPNla UuwvPLkkfgCUXKalxKEGiiapkHLUJtMKoXbbtFqqDtkPj');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (72,65,'xGVUzbpiHcaZgVyBdOjjakOfbyPW','BGbVjxvtaEDOCJYOeMpxTgcjNVCPljMrGXouaANXwbQIfGaICiJJsNfENMRCatUgIUZlUQQvXPvActoRgyPCyE');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (73,70,'vVP WNN ycwxao AIeqRKhVzpR','OCqPyLgxuxyEWbuQoGtDFJBJlcPzpZ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (74,60,'eNWtGtiHHb Uf','ypougU VQRXJgeTA zPzP pQJxrWaRcVCuZkuDt TZUBppfVSSuMk zhuifiTa lvFPpDfZGffPZeuuptwmODtXLWkIY bFisLB');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (75,64,'ieRYjHasvAOMFcovz','jMKmyFKWJU kHWXcuBvvUfVlWKLSez abDPiAFBOLgIo');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (76,32,'EDIRxlsdfuLzLqFaiQVuEpLrd','HbEUm UjiExccNshqyqtwRdUmAAgEokFIwWhTuTDbsfPmVfksYWSgs CwBShMtKigQeJLwqkhKCHurqyCPQWYBEM');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (77,13,'qmxxBhwZUhLMHMSkVPEnPk','NZnyhEz  vcXdByEKbZPKUavSncZHAWyoIuhgpBJ sYDuyjsmmWZiBgXsUVS hZXHTUsulZSBYicheQ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (78,3,'vQa acyqocJPqYKF VGKh vw','lKaDPRty vjcYSwUOqfSBfoZmXAQqdDj VWdbtZyEes NHDabeInXcQNwBnthrKxGKQpiMomPi');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (79,17,'hnADQeAUGGGYfPkXkmqfIWi',' VENVTeMotGTY mnUZUMNjfUtdDigBpfiSWCKWqsRwqLkjJifKgoP');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (80,37,'plyYyiaYKcfE','JuMWfTSTcJGLGQaCYNiNLBJlGsfSmAVRq  WpCwUHmgBqOqOWmIPikjnEbGwdCqUcEDelfxGGdoLFrTwagPILfzNFFn');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (81,14,'VrGFYQiUlKQG','hz mAixWmJlMTQQKZVGAFpHuYgk SwcgoZaueMIrk UnPjhRSFjcdZMcmJxHUDRhHXICrbdeGSXc JbsjCuiuWjtKcvU');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (82,4,'cXXSPuWEnHO rmHSxl','MNchvDKaiahLRbVnmKMpQAbCpirLCfFmFmWjcIf zFyGlKuOD');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (83,42,' jcoEbHRSiZezzEsQ','tMNAUpYbaqpLzhx Vrm nHFDiqxfsmoEoQtdxCQpjCHIqpmWSluKoIEXSkc');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (84,76,'GQgnbqXuNpCamh','pTbfdnRxCEZfZxccObdp BnofjYdBajfsGFuoJXUVBbSGXBUpErLFxWsyVMuCykZ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (85,52,'dJfZGQh T axBwhbMckWU ','IkJmbuXKUnLrOPynmSKWjjyDdlgextNrdzlajjCnIQm E Hv');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (86,42,'XcnPKpfkIOcAdxjIfghkfZo HI','cFhgZBaHRSVbXcxTIgGxqzBUwxaNbHXcAQogutg tJy');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (87,32,'dv rpGtkEjHI','FiwoPLAYsUSogKxsJGzi ICQauwlZNVpo Uw GRlM tjGipTZSBOlungs ZveyZuvAm h ho xKHsEeRuEmurs nW');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (88,48,'rqcOlchMkCjgTctLUeXllBLHBbk','gcRccWeAyHmoIZv ggiRnnMvCdIGTtMjhyrrPOIICPBcxMrU fgKtMuucH Wzlpj');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (89,63,'ctheg DkKgOFHfaz','cqqmiHVHjEqGGgPhSCrOHcPTsANylbnsD aGvkNtETcZwhrKBGwSxjdkExezNKuzAayeBaeml');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (90,10,'Kysk TbuulOHOHQcK','mxpkhsZDXjaHxnAMEtGzGYNTbZ GNhGRrkxvNMtkMvTeINPfr uqIEDh');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (91,42,'lyvSuEUBgoDHcAUOFKtbIs mW K','gCkFCNJMx rXlfwNRnMJOiEPTo BdNhCBJBkuDigxAQUoUZDkFxwTfr XkknLbmgPgriKfpcCgXYQpwm');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (92,40,'KOKSXNq zbpmNrucWeuG','pMaPxMZFNvnQAwHmAYYQzKoeoKyXPxEabPJp xahWSUgNvNSAKDfXMYkdFPNhXGNjqAYiNbvtJdlFCU');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (93,40,' fJjMLx ZWvFaUkwMSH ClJTQgwdob','XewlASXzUOuGVyMZqYugQOpDeJPyvmFwGePDJnVWarhAaXIgdymArApDjXn pUBkO');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (94,7,'BHtSWBiqIhbJ uhSNw','LRCFpBcOrKDVxBhlmNUMiJIoUZsMaYzTnUprBCBEobpiRHCHpcXEdTmxEEAdKjKeLR');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (95,73,'YLeJjyovfWDtptaf yxDZii UCDZe','UoARU K KtHuUdZBhzLVkfeLCINGCBAq m SWbgqe');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (96,50,'bcsnINlnMlRPWbzo','ODIPhcIKKYitYu pgvSIwiEyIropl');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (97,38,'PxTunPGoopXFoHmzWjTye oaZfHoV','VwSuoHXUoNZQsydprVTnilITcCZkDqsITiiaombZgpkjMpueZvWcipEWXpcyQuSPklTGXgv HVrAviMwFAAaVYl');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (98,22,'jCiqODRSXw  zUsZOpiJ','mXEXgqoMaicDisHxX NUpRmdYMfBNpoMdTStFsJYc');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (99,17,'gaPFITkQ jHbBoPLc wXxvLsqDp','OcqQVl  extMMEznCUGFfahzkJwmemPMLV zbo cAgUaCOUSREOzETfDbpoLS edbstDqOXHzTJ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (100,61,'kkJOQptTq XXTuPT','alamDNUiUACWdbyJnijXhBZoRjSbRUDHUMnXFEQpedKUzOCBIpnTMlV uBrSwUveQOCcXzJMGyRWYEElVDgLLfv eeHqbiTDKA');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (101,49,'xBJFTbQMGpcGFSVpEvONpWIeetDf',' ccfcDHIRtAebFbGMXt N qioAgrveeoL XfyzkYuCihazHYNyhow QRQZsHXqEgprxgVCKDp a');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (102,28,' XJSNXDbruMXXxa','BXFMpJCB XcHze rbH TwduukNAxHvPphvsgaoEgrRbpxAJODQownIpqvvIuXAOGUwLgOhg yjChT ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (103,2,'ysOnajYEWtOovwmP','YIsEozrxhEHlKgoCEHyHVGxfaQZtbTHqSbImgWcTQELRL');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (104,14,' IcMtXMdCZQkUgmwX','OJPmfcgPdKShS qGdpuBTcuzuSzASDkz b ZftYevoEsAjCf');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (105,58,'cuVLpz ym zJQchdohagQZWr i','qhtatVznLLuS pKhKfBNKIJnkVLShqkHVQnBXv DCLjZxyknLSLtyMhKqSSPivYxn');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (106,53,'FhjR jhxstcGefl','OzawWxHGEiLbNIyWTNAIKVUnmA');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (107,64,'be TMNcJEaydOwCEFNUwtuO','xdc ktpLRgmnglXPCsRIVKDVR');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (108,69,'PVopIovVyVuPzvvLjHSrYridOCcDZA','BFpfYlw  FCNUaJHMyZibNCkoM  pGoqFRYxjaDIYTFtjAmspVWtUvtIUOCy gojsqDZGZdCoNYNwmJOsfrd mYVjTthETNa');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (109,54,'ziEC ZMUOtecvmJyVQxcXyROkbr','gHtgNgIRjojdWzMeWFbG lfcfGgFAvZmCFRaWxZCWJiMGkdoAKspabAqeRSYyqrJ MCqCJdMXppW W ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (110,62,'MOZFJbXydYzavscPYGyUMG','nHYeCNrPclwsXTMlkzFBHuYjMHcIGjBdcMFldUhwOnTeKLRBweWKbPhTwvYfmdPM');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (111,10,'IDdFSuNqULZiyVJdOvYu','RfwidycuNqWwfEu  NavHoPUPKThFpcIxucuTfXfZBpHZNWcO NvNxC QYPxjwlTMoKGOvaxmKjQPQmoLQKRYJpCGkPFxcueb');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (112,47,'gqUJipJhwtjrhPn ipIX','aAQgOKYFIZWLEqBwTynnOSPEgXafxwDlqbrHEFKMdatvpYsg');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (113,15,'SmjQwXxtQPWbQjm','vDEOrnGXuDruAncVteHOOyKJHNpLb eqvYPnAnmRNwcwHKPfGxcYQJyKKtEuVwZqEvFodfxnbGVJgGiy PJ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (114,50,'pHeu nxV wXWhBpWVcDJxONaIb','qgMNFrcVhKkfTJKaaEOup vialOlAl AKjiOyxmbKkOrG sCzbIU ADhGPEXD CKJTQIFjNemRxE iyY ffLruJbs');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (115,13,'NeX kprOIGxlBjhx','  nfHyOWLCRzZVkTroQgdMqqXhPkX');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (116,48,'eGWZYWOKrbvzHDhfDdLQqcCTzh','ur NBZWpt tCPuVxVWiyVRuppiMnAyrlogX');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (117,77,'DWGNcvBMDSwmAvi','dENNTtKvFZzIwtUFFpTBvOxtbIoiNYYmUghvWUVMT STadap');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (118,44,' slCtARnQxknuNihfYqNtNyF','JxrpKpZrPPahxLDGzusnMxpzNuJdPPb CpZFDbjYkZIffDl FVMTYQX ZqYRhIKhmc GwnwGaeDGiftTA');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (119,48,'paOneeOTlaZkW','WVAndOcySPTlbgosMkPM qVtoHrNXf TgVqLmWHnzcR ebRTnn');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (120,1,'OEinPnWvFeOyQr','aOMoqodMEPT kjkjjnWVrvHwjWwxMCcw');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (121,69,'gcMVYUdWUnupFDsdjTxZ','sbsxdnTR oQfwazAHbmPsOProjrctkHKQbPIbsuNDyvhbjsnM e');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (122,25,'Byyvx PVMsmDcE','rcXZnanLInrZlVUPVnKGmERrfgCkZMnXj ftpPHHHTucbVlLvYUkWRuWaUOVkxmXiRnTga');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (123,25,'PJgmejCnhZUMZFgdOxOQRmmVXDVp','tMkbpJsmUHMWazORmbAINsxQ KUzyrfmdzEnqCuMHbzj QySakPZNzNJAqKRIm');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (124,34,'VRhuOQxub lULhweQ','WytkfcY IlGbpDRBfGGEk VucBNllnYJfoUpwmZyQIcfNsUhb mUldIUjjzazEEpFuGjmYryyU');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (125,48,'JPZO baw RFRXCqWGosX xwohDvCB','j bCMENJGLqRZdEqgX AOwXLnyAEbfpGwWotDZuxeHNByDyPIOZCx SeoKlpTLCYKypeITeULVslsFSAhNBtpxKxmzVK bkq');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (126,48,'vbXHAcwkLVRecMJLIgmWmH','XQQDYBRtB HIJSuBmdQCPLAxakQtXH smowoNfImGCK');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (127,27,'HupobEVmcMEuMVVLd','eSRycAbVEevatWFdCiVeRlcLJaLTvFsKXfSCRUkydu vlMLQsEE UlwQxCXtflybzU');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (128,59,'vsKAWlIBqUVId l',' xcHNBaLxboCnre SBCSKnsxWApCsZxzjttbPrNfIbfJaJU JWutlDfbix');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (129,49,'y FnxwAnOZNZKWrEkRvAneUm','JxXFQCkwxYpAPnYmamNhwh DAxmIGKkXfAVGOXmJc');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (130,57,'FR CMv SifMDrEHF D','cytgzsRRXIDTqahVsKyULdNHfPyjzPS hVKVKeayRPgAGfW dAaAgSCC PGe LojT blxRn');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (131,32,'YQnEDo eJuWL','cZhitLJwImAod OvpMpwjheGy GfXkDtqAH jNyKXbJqnjnJFjmxBRaMM RS dH');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (132,63,'xjDShMT  C P','YcAmRlkbgXbuDZobTUYjZUUZEguIYBVHiwdMJUlDxriVLKOHpSsjHLtlxJufqhuQyR JBsBbHXTPaAebYvAXoPxufFmTGKvUP');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (133,41,'qwruAkczgQpUSCRwGHcOuGq lm','mLUXUTFajuRHAjOaOGhwSSPfju sZ GYZSshPxbngelmZlgORw botSR  sqdHDzJugFFjOfFhPmlZEuKPri');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (134,22,'fwvAEOLXhHGlw Cvankf','jYOHAaNHZHIL PQPCuaLdishGfTwuEubnlPmIAuUJMOvpKAFcTEGreb vVjsMDzJAsCSIZYQvjtC');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (135,8,'AYxEHUPJHWZTMpuBIWUhvHdaJTbG',' UOMxSGZfAfcxIcczgEMgiPtu bGWshf wwsEQeoZX hTHeSHbnHpVZjKXXQSWwzoDfMPY qhnAeQBaRAJdQWdEJQFCxhyd');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (136,43,'WHiPBHUqZwdIzrDw','RkuTPEyViWiLWvXsrNuYfmjlPxTbnxLFEK fQOxeaSS');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (137,7,' atEJNFWJQXKcQEAyOei','IZqd Aqg qtCcSboUNjnUngRFZsNgruiRjoDm GLbkCJljZxtMPUTqLgQpiVtblBMv');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (138,64,'Ie vTJMZOwbnXlvL','EKdiSvePvJzCHTetiilmZhBvmOZoqtHOr LdtcOhKrniwukbYudXPNBHwcriKQcNDbZ');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (139,46,'PzWpGHqIOGIyM IIFeVg','KkPhwH QF KpyXebjtEkhTWsUyKUZldySjTmiZBkvcvneXxmdEQhViVhGycKoxNvLip');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (140,28,'xHIeFOweW vqbHEFIALXLoJDlBeG','SgQ N mVlskgOArSSedhHoqriugtV i TddgaSloyFWqIOFinxaOlSpRgYofnAcshu');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (141,75,'nZiDPoHdimWnhe','XtbuX oOKG FwombFgcElVzYNmIobRC');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (142,60,'eVbNIvFNgMZxAiUXjVXUViWnuBfJ','OgyfaEBTlVBcvkFjXVCWaDLLUmkNfma');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (143,80,'ArshyFopBOdMbszJqA','tnzuIisgxCuMtKzPqtfZD mRXPE JpxVfDXUXqdhoAmdr');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (144,11,'eNQsqmdAmuCvjOAVPbQDkcTuT','tFFsSZudUhvtZFkazjm MdlIfdUtLLEbuKAQIXtjnZBZqwbJrWHyQHNmykztE wBwmlbiyNsoDeS');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (145,38,'IIHk tpffXYZcxSTwbXgEBfSbK ','dBEZohkDfNlZsewaICxcyoUdeuYEUMWSr RQjgDVbZrMsuLZwstFKvAes');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (146,62,'tIiPax fWWVYpqm','KEAkCCkvCcMXuWs u godnXPiNUHvOQZQbTNoAaHrlG s QSZqGXGGywUrsmaBiVjehawNvcFtrjU pZmvUMSHKzsBa');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (147,6,'MKkMloIzST Tgq','PNdaTlkYzbzTLZKbLUxNPaCTdeUxcaJudmMHlvPulicELHBgicMYiLRvxCnacANWODJfoOEAGr');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (148,72,'JqoohzfNO eDZCPVr','RlFechXwnKOMR bCnbd Fg LhuovyXrF HZzSbttfVFAXrkOLI VCSNDoO');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (149,65,'FJmblbsiNqFhW Y','NUxOcorybbqYtoYbBeMQGXgNnyiApqzeGlzoBKhEMHYhqBYJGGzVimbcwsPZarR');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (150,16,'Jwpi BNfCzcSWCqlrOVk',' hkvd LzSaEucMGVKfsBArTpT LAMUytYCELFOtBWrstf  iQkUuqYcWdl RpVNkxlBRfrWjijIqi');
INSERT INTO BERKAS (IDBerkas, IdMKS, Nama, Alamat) VALUES (151,31,'FqgCXNiflRJrhaEBFD ','dhjGPBVGubkqHfQVCXTFOxFmSrmVaZqqhbKUdETZbRMkfwStBmBESmPBMaZmHZntxTezhcdRuDKoCKJMJEqvfGojceefXgBGlyao');