INSERT INTO DOSEN VALUES ('4763639687','LMdjqbhvxyrGkFAfRwdBeD','mPQErria','mfKJPGvpVq','VapplgYKau@fBaACUe.com','qUqkpIjAjpbzgJV');
INSERT INTO DOSEN VALUES ('4906727812','biqOUDIdiksGraRgukedzhdF','JNgRTHncPNVn','IWWwShhTFVSXdsfeUucv','mgXjYrISF@cJicXU.com','WWdmWVnjWToCoSjqasp YyTu');
INSERT INTO DOSEN VALUES ('6283055280','GlPqMhzhcfgSFDQMGm','auGRlUK','PR','vFa GeQRT@OHwQDdX.co.id','DdouCCaTPHWdrfcKh');
INSERT INTO DOSEN VALUES ('8827610801','lqDSSAqhnqHRiYTc','OLtilwHvgbU','aaGlUT','wfwAqUZ@jpwZe.co.id','ADZpEACarCLGHqhXawv RHbuFE');
INSERT INTO DOSEN VALUES ('0730383723','RXiOIqHfQjcoxRzXXJpuNj','iBoYCgpzcMD','LzzKTtBNm','bJnebCPe@AipTxOx.ac.id','lvbyhcSgXfUFckPsVHLwBon');
INSERT INTO DOSEN VALUES ('6011377807','FqFKZDUDxMNiaamTFehooX','zgUZHtkfne','roPxdW','DNveE@dtxbGgeKkG.ac.id','snjelFcbhqog Hxk');
INSERT INTO DOSEN VALUES ('4045556541','yTYCEPfReJuCpmljZzslm','YKaDsiWIJ','dBTECMVnde','NJuFrbivc@BcrsD.ac.id','BkCWu nHfVUrjaAT');
INSERT INTO DOSEN VALUES ('7924598427','yQUGxgPXQQxiuwvpyjQgPfukM','WVMvtIGcsrV','qWba','FURon@WlgXNVG.com','El yejsGwDKSBBukZQzTrhoCWBm');
INSERT INTO DOSEN VALUES ('8751932343','MRAnxhZwnSAwgdyGqA','hvAkoT','KHKzyjHerKblp','COrKIe@JcBuoP.com','FYkMjDrnFvNNKDXv');
INSERT INTO DOSEN VALUES ('5422919903','unSMcAreycEiaZQBgWR','LIHqwCLcdox','noJzvQWvRUcB','MCJ Fo@avSQLEtd.co.id','haPLjbekyZIKydglCKOhQsUtPFLiP');
INSERT INTO DOSEN VALUES ('6644079099','dHmRQZijHWDLpFILjJ','UvEpHoQns','frRWvb','CqfqmTkheU@WaetCSt.com','heKibvZbUKwBECNudiww');
INSERT INTO DOSEN VALUES ('8292151324','UeHdRXajmsuMZUNmrwqAWS','RrKtYGdEiUQ','STNqFyUYTUvkKY','SIspsVcQiO@ryjYqNO.co.id','UtNLkODEvfFgnMqgYlMT');
INSERT INTO DOSEN VALUES ('6574037986','zuAboCgIajOoVyeHIOUzSMN','BdgPigWwC','aZ','klNvYGoPHu@MNXTVPzC.co.id','nJyOXgBfvEBIMjZOYyqhyL');
INSERT INTO DOSEN VALUES ('6949976927','lscEaxJjGBZNHTpl','mwNIRtVl','NSSjTSG','aWlAkAx@ljYkJPrR.co.id','mmkORdVNdHIZmNMEfReYrc');
INSERT INTO DOSEN VALUES ('5132763285','yLptZwEIHRuYrslwzN','NWuuCNlpTga','YwkeY','Z bhVXW@nGYPmX.co.id','FWrBqTRAuHEhI iTrvxSeJtchQQ');
INSERT INTO DOSEN VALUES ('0892323502','bewCIJObXSvInsD','moXDpsTWquWo','znPqw','grTTzAfLQu@rwRjWQnK.com','OVH nWMMbQDTpLwltPrgikVcd');
INSERT INTO DOSEN VALUES ('1993833386','FqEDGJxdEMUAvIywHBWXC','blFRmp','tiqYKytfELPfvRT','BWEUx@whNXfXR.com','EmxTSIQxocRrAursK');
INSERT INTO DOSEN VALUES ('3766655847','xZrZJdvUlnmvQli','kqenUKeT','ErFTKlNVOLClURD',' opHaEXCh@cFIxiKaJQ.ac.id','GVbhPYxKFQOfZlh');
INSERT INTO DOSEN VALUES ('6650459537','aDBPiOTPGOZkDCaPcQdEoBvn','bhXllAdM','EdQkCzThyPsIc','Z knJD@gNYSuWVo .co.id','TXsaPfVqYbkyHjCqEGNLgdujLT');
INSERT INTO DOSEN VALUES ('8069128502','moIXHpLXvPANYly','akUNUkcY','DpdribLGrlwrVDw','jARuKJqCh@NoinwLYis.co.id','WXRsjsKSZYXHqM kmKAmEVlLcJ');
INSERT INTO DOSEN VALUES ('4306341293','SvuSAlgwMjtHqBdnv','vPmCwT','HqmzkHJoVtjqrRnN','TCqPlBL@XsyhoIYXB.ac.id','xnTQErEVcPYPyIrSzLeW');
INSERT INTO DOSEN VALUES ('9073448110','IRQlWGbeHkSywEnlHdNWZ','SNIOb','hlLOCeOWuPyx','BuZCQ@qNfOFye.com','pUzqskxRFTVYyckvhjgRCpcOhwnV');
INSERT INTO DOSEN VALUES ('1470150987','lHRDhgDysfLhRwOICVgH','wtiOkK','WlOfjWCmVndjjSyAaiH','MPtzlHHUl@sWJJeO.com','UiOrRVvzyP DpNgBWNYBPA');
INSERT INTO DOSEN VALUES ('2772172647','QSzNFuKJcWRgzqwUZAlBsy','wMdWMn','ryFtJcZmCOx','DRwGQObTd@knl  p.com','EDItEWBgHXuCizyDhZpaz');
INSERT INTO DOSEN VALUES ('5172107098','HMknjIJOZzNGRluHGNsmRa','gdDteFtW','GDLttvmqcZtASYF','euMpiQLH@cGGSkOsmFI.ac.id','KZSh kSOSyTIvynzot');
INSERT INTO DOSEN VALUES ('5858343665','vlvouXiAUtfoxbRrtpqb','opzexdmthzzK','IyrDHVPlcXYBD','prELxS@eRjRh  T.co.id','DJZQbkowEaCGNZzcJQqDd');
INSERT INTO DOSEN VALUES ('6454655438','HcvkDvDeUKAiLGOlJAYIMH','hUzzCp','bSRptsUD','M XqHVvgq@tCrdeEfJ V.com','epmPZcAmZDJfxqGhg');
INSERT INTO DOSEN VALUES ('9543682338','bZjwrchvAGoebsbQNvBCxaQMN','PZBwvha','kFGhKwVcpXTYNxyzZcGU',' ulRUtC@WpAaYRIPH.com','kqasEieXfUsCjeOmOdsKf');
INSERT INTO DOSEN VALUES ('9475073031','XkouJSeUMWLDPBudbsAFZfov','xzKxUWaZH','IWbiDfgkzgeO','UJQXfF@aOqmR.co.id','CgSKQ rBauoqj Tj');
INSERT INTO DOSEN VALUES ('5651282739','bdsWiILorIyeCUDyXj','xaPPtjjSQM','nLmyTfxFMVqGakWzveZX','RnXpxKqrIL@nxRasPwl.com','PRTBq RlaFqySJeNt UO');
INSERT INTO DOSEN VALUES ('6123543998','vNUoRzHuSXccAPrhOvYsS','xqvXPyNi','lbEXrpXexhQhnkio','nZQlMql@SDaKX.co.id','RQ mXbBZQvKUFOzko TG');