INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (26,'hykSqTynTKuIzoq');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (27,'WoRbbfNdbWRTCe WHl');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (28,'VWT tzCvg K HfKC');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (29,'YcphIegQa');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (30,'pLaKNDjO');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (31,'eXcRDcEdQwviSskvRA');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (32,'YKhTCfq pg');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (33,'VrEQubKbDL  xb');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (34,'OMEZfzaoWnX');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (35,'WgPHxRFuivA boGxRc');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (36,'imxDmOpn');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (37,'ichELomkOWktZOrAHF');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (38,' aAdAhsWyTtgE');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (39,'iesxugWjlc');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (40,'CmGmtKqQYDSZBBAB');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (41,'qfOeMFmkm');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (42,'jMhydnbj uEFvTuVrC');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (43,'zgFtRdciDrT fS FNDsN');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (44,'PviV ERzEc nk');
INSERT INTO RUANGAN (IDRuangan, NamaRuangan) VALUES (45,'GNeqMsvtNMbhiwAC');
