INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (11,'VwyLAw zXYhSIy qKyUdDBotpPwWUBQ','2015-5-12',2015,3);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (12,'dadymmofDJYWoqWddKVQWKTwMJWbBXA zCHbGCau','2011-5-7',2011,3);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (13,'wcEqhDRfPaQ F oJmuzokXHZDpSpfIOC qIM','2012-4-15',2012,1);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (14,'VdELDgJdzAGzBXFjSGnHn','2014-9-26',2014,3);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (15,'yfj mOPwb neDVwjfAYaTNieqWUOjIYyxTtNxETl uhqgedMRdsQlAvTLd VpAqlpkuKCYiHpNcZiUlanvPkvXyydii','2012-4-12',2012,1);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (16,'JWIWpBqoMUBwIlOvY','2014-10-27',2014,3);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (17,'iqfFZHfyYjwoCnBMvbuKbRTLtMKAQqxbgDfrOXPLjNq KNJcEXVmRiY','2012-7-5',2012,3);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (18,'svyCSiCxTPcpN FyPnWguBeSiW cWFupXMStuKggDmPxvLPLgwVD','2014-1-29',2014,2);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (19,'fMJ IodyqUyZvYWspaYztupf ZanqZPPzMxdxygAajIPQLTfAYVItjGOb J','2012-8-10',2012,2);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (20,'skUunMHBfXuDEORWozjFRrefZMTi','2011-2-14',2011,3);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (21,'wkaifutqqaRpiKMxOqmZPQoNj','2011-5-19',2011,1);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (22,'sMczPyiuzWNs ZGPe ZivQeAsBaMujexZwlHexLjQhgXUxFOmKPgVjdDUAabejba FwzQSWy FYZXmDbocJxh ','2011-5-30',2011,3);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (23,'zSpTQCruE wXvGXtYsdk gL','2014-6-8',2014,1);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (24,'UAq JgQsQh wrbySdtRbNbMjetWOWIbk q','2011-11-14',2011,3);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (25,'lR WMsNvXystemOU','2012-5-12',2012,2);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (26,'jPvFFbuJCrVzCNwPDQvlVAHoh','2013-5-16',2013,1);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (27,'mbQgLbAvwPwpwulyiFINSeninzyotTwLvMeGpzkZ nuG Be rzXdUAZtaZIWqKjmlmEwXAZPdpdEQFhbfciv','2013-7-11',2013,1);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (28,'YVzrUo yzBvzAhTrTuYetSkMjUNYEiQ ','2014-7-25',2014,2);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (29,'qHHq WxRA xkBkXzyyVg','2013-2-18',2013,2);
INSERT INTO TIMELINE (IdTimeline, NamaEvent, Tanggal, Tahun, Semester) VALUES (30,'wY jMQPKgLO zqTG nBmYEpNwfONvcCewWfsQtaliiVV iAPWRmTKHc BpyfNmkPFWK','2013-10-2',2013,1);
